/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
// Product =
// Alignment = 4 bytes, padding disabled.
/////////////////////////////////////////////////////////////////////////////////////////////

#define _CRT_SECURE_NO_WARNINGS
#define EPOCH_GARMIN_OFFSET 631065600 // UTC 1989-12-31T:00:00:00Z

#include "stdio.h"
#include "string.h"
#include "time.h"
#include "stdlib.h"

#include "fit_convert.h"

#include "fit_product.h"
#include "fit_crc.h"

///////////////////////////////////////////////////////////////////////
// Private Function Prototypes
///////////////////////////////////////////////////////////////////////

void WriteFileHeader(FILE *fp);
///////////////////////////////////////////////////////////////////////
// Creates a FIT file. Puts a place-holder for the file header on top of the file.
///////////////////////////////////////////////////////////////////////

void WriteMessageDefinition(FIT_UINT8 local_mesg_number, const void *mesg_def_pointer, FIT_UINT16 mesg_def_size, FILE *fp);
///////////////////////////////////////////////////////////////////////
// Appends a FIT message definition (including the definition header) to the end of a file.
///////////////////////////////////////////////////////////////////////

void WriteMessageDefinitionWithDevFields(
    FIT_UINT8 local_mesg_number,
    const void *mesg_def_pointer,
    FIT_UINT8 mesg_def_size,
    FIT_UINT8 number_dev_fields,
    FIT_DEV_FIELD_DEF *dev_field_definitions,
    FILE *fp);
///////////////////////////////////////////////////////////////////////
// Appends a FIT message definition (including the definition header)
// and additionalo dev field definition data to the end of a file.
///////////////////////////////////////////////////////////////////////

void WriteMessage(FIT_UINT8 local_mesg_number, const void *mesg_pointer, FIT_UINT16 mesg_size, FILE *fp);
///////////////////////////////////////////////////////////////////////
// Appends a FIT message (including the message header) to the end of a file.
///////////////////////////////////////////////////////////////////////

void WriteDeveloperField(const void *data, FIT_UINT16 data_size, FILE *fp);
///////////////////////////////////////////////////////////////////////
// Appends Developer Fields to a Message
///////////////////////////////////////////////////////////////////////

void WriteData(const void *data, FIT_UINT16 data_size, FILE *fp);
///////////////////////////////////////////////////////////////////////
// Writes data to the file and updates the data CRC.
///////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
// Private Variables
///////////////////////////////////////////////////////////////////////

FIT_BOOL GetStartTimeOrWriteFitFile(char *src_path_file, char *dest_path_file, time_t *start_time, const time_t *offset, const FIT_BOOL *isWrite);

FIT_BOOL GetDateTime(char *argv[], time_t *t_of_day);

char *GetDateTimeStr(const time_t *t_of_day);

static FIT_UINT16 data_crc;
static char buf[80];

int main(int argc, char *argv[])
{
   if (argc < 8)
   {
      printf("usage: change_time.exe <fit file> <year> <month> <day> <hour> <minute> <second>");
      return 1;
   }

   tzset();

   FIT_BOOL result = FIT_FALSE;

   time_t t_of_day_new = 0;
   result = GetDateTime(&argv[2], &t_of_day_new);
   if (!result)
   {
      return 1;
   }

   struct tm ts;
   ts = *localtime(&t_of_day_new);
   char buf_file_name[32];
   strftime(buf_file_name, sizeof(buf_file_name), "ACTIVITY_%Y%m%d_%H%M%S.fit", &ts);

   putenv("TZ=UTC");
   tzset();

   ts = *localtime(&t_of_day_new);
   t_of_day_new = mktime(&ts);

   time_t t_of_day_in_activity = 0;
   FIT_BOOL isWrite = FIT_FALSE;

   result = GetStartTimeOrWriteFitFile(argv[1], NULL, &t_of_day_in_activity, NULL, &isWrite);
   if (!result)
   {
      return 1;
   }
   t_of_day_in_activity += EPOCH_GARMIN_OFFSET;

   time_t t_of_day_offset = t_of_day_new - t_of_day_in_activity;
   isWrite = FIT_TRUE;
   result = GetStartTimeOrWriteFitFile(argv[1], buf_file_name, NULL, &t_of_day_offset, &isWrite);
   if (!result)
   {
      return 1;
   }

   printf("|%-10s|%-50s|%-30s|\n", "Type", "File Name", "Date Time (UTC)");
   printf("|%-10s|%-50s|%-30s|\n", "Input", argv[1], GetDateTimeStr(&t_of_day_in_activity));
   printf("|%-10s|%-50s|%-30s|\n", "Output", buf_file_name, GetDateTimeStr(&t_of_day_new));

   return 0;
}

char *GetDateTimeStr(const time_t *t_of_day)
{
   struct tm ts;
   ts = *localtime(t_of_day);
   strftime(buf, sizeof(buf), "%a %Y-%m-%d %H:%M:%S %Z", &ts);
   return buf;
}

FIT_BOOL GetDateTime(char *argv[], time_t *t_of_day)
{
   int year = atoi(argv[0]);
   if (year < 1900 || year > 2100)
   {
      printf("Error: year must be between 1900 and 2100\n");
      return FIT_FALSE;
   }
   int month = atoi(argv[1]);
   if (month < 1 || month > 12)
   {
      printf("Error: month must be between 1 and 12\n");
      return FIT_FALSE;
   }
   int day = atoi(argv[2]);
   if (day < 1 || day > 31)
   {
      printf("Error: day must be between 1 and 31\n");
      return FIT_FALSE;
   }
   int hour = atoi(argv[3]);
   if (hour < 0 || hour > 23)
   {
      printf("Error: hour must be between 0 and 23\n");
      return FIT_FALSE;
   }
   int minute = atoi(argv[4]);
   if (minute < 0 || minute > 59)
   {
      printf("Error: minute must be between 0 and 59\n");
      return FIT_FALSE;
   }
   int second = atoi(argv[5]);
   if (second < 0 || second > 59)
   {
      printf("Error: second must be between 0 and 59\n");
      return FIT_FALSE;
   }
   struct tm t;
   t.tm_year = year - 1900;
   t.tm_mon = month - 1;
   t.tm_mday = day;
   t.tm_hour = hour;
   t.tm_min = minute;
   t.tm_sec = second;
   *t_of_day = mktime(&t);
   return FIT_TRUE;
}

FIT_BOOL GetStartTimeOrWriteFitFile(char *src_path_file, char *dest_path_file, time_t *start_time, const time_t *offset, const FIT_BOOL *isWrite)
{
   FILE *file;
   FILE *fp;
   FIT_UINT8 buf[8];
   FIT_CONVERT_RETURN convert_return = FIT_CONVERT_CONTINUE;
   FIT_UINT32 buf_size;
   FIT_BOOL flag = FIT_FALSE;
   FitConvert_Init(FIT_TRUE);

   if ((file = fopen(src_path_file, "rb")) == NULL)
   {
      printf("Error opening file %s.\n", src_path_file);
      return FIT_FALSE;
   }

   if (*isWrite)
   {
      data_crc = 0;
      fp = fopen(dest_path_file, "w+b");
      WriteFileHeader(fp);
   }

   while (!feof(file) && (convert_return == FIT_CONVERT_CONTINUE))
   {
      for (buf_size = 0; (buf_size < sizeof(buf)) && !feof(file); buf_size++)
      {
         buf[buf_size] = (FIT_UINT8)getc(file);
      }

      do
      {
         convert_return = FitConvert_Read(buf, buf_size);

         switch (convert_return)
         {
         case FIT_CONVERT_MESSAGE_AVAILABLE:
         {
            const FIT_UINT8 *mesg = FitConvert_GetMessageData();
            FIT_UINT16 mesg_num = FitConvert_GetMessageNumber();

            switch (mesg_num)
            {

            case FIT_MESG_NUM_DEVICE_SETTINGS:
            {
               FIT_DEVICE_INFO_MESG *file_device  = (FIT_DEVICE_INFO_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_DEVICE_INFO_MESG file_device_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_DEVICE_INFO], &file_device_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_DEVICE_INFO], FIT_DEVICE_INFO_MESG_DEF_SIZE, fp);
                  file_device->timestamp += *offset;
                  WriteMessage(local_mesg_number, file_device, FIT_DEVICE_INFO_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_SPORT:
            {
               FIT_SPORT_MESG *file_sport = (FIT_SPORT_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_SPORT_MESG file_sport_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_SPORT], &file_sport_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_SPORT], FIT_SPORT_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, file_sport, FIT_SPORT_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_TRAINING_SETTINGS:
            {
               FIT_TRAINING_SETTINGS_MESG *file_training_setting = (FIT_TRAINING_SETTINGS_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_TRAINING_SETTINGS_MESG file_training_setting_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_TRAINING_SETTINGS], &file_training_setting_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_TRAINING_SETTINGS], FIT_TRAINING_SETTINGS_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, file_training_setting, FIT_TRAINING_SETTINGS_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_ZONES_TARGET:
            {
               FIT_ZONES_TARGET_MESG *file_zone = (FIT_ZONES_TARGET_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_ZONES_TARGET_MESG file_zone_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_ZONES_TARGET], &file_zone_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_ZONES_TARGET], FIT_ZONES_TARGET_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, file_zone, FIT_ZONES_TARGET_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_TRAINING_FILE:
            {
               FIT_TRAINING_FILE_MESG *file_training = (FIT_TRAINING_FILE_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_TRAINING_FILE_MESG file_training_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_TRAINING_FILE], &file_training_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_TRAINING_FILE], FIT_TRAINING_FILE_MESG_DEF_SIZE, fp);
                  file_training->timestamp += *offset;
                  file_training->time_created += *offset;
                  WriteMessage(local_mesg_number, file_training, FIT_TRAINING_FILE_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_WORKOUT:
            {
               FIT_WORKOUT_MESG *workout_mesg = (FIT_WORKOUT_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_WORKOUT_MESG workout_mesg_tmp;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_WORKOUT], &workout_mesg_tmp);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_WORKOUT], FIT_WORKOUT_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, workout_mesg, FIT_WORKOUT_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_WORKOUT_STEP:
            {
               FIT_WORKOUT_STEP_MESG *workout_step_mesg = (FIT_WORKOUT_STEP_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_WORKOUT_STEP_MESG workout_step_mesg_tmp;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_WORKOUT_STEP], &workout_step_mesg_tmp);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_WORKOUT_STEP], FIT_WORKOUT_STEP_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, workout_step_mesg, FIT_WORKOUT_STEP_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_FILE_CREATOR:
            {
               FIT_FILE_CREATOR_MESG *file_creator = (FIT_FILE_CREATOR_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_FILE_CREATOR_MESG file_creator_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_FILE_CREATOR], &file_creator_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_FILE_CREATOR], FIT_FILE_CREATOR_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, file_creator, FIT_FILE_CREATOR_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_FILE_ID:
            {
               FIT_FILE_ID_MESG *id = (FIT_FILE_ID_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_FILE_ID_MESG file_id_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_FILE_ID], &file_id_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_FILE_ID], FIT_FILE_ID_MESG_DEF_SIZE, fp);
                  id->time_created += *offset;
                  WriteMessage(local_mesg_number, id, FIT_FILE_ID_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_USER_PROFILE:
            {
               FIT_USER_PROFILE_MESG *user_profile = (FIT_USER_PROFILE_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_USER_PROFILE_MESG user_profile_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_USER_PROFILE], &user_profile_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_USER_PROFILE], FIT_USER_PROFILE_MESG_DEF_SIZE, fp);
                  WriteMessage(local_mesg_number, user_profile, FIT_USER_PROFILE_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_ACTIVITY:
            {
               FIT_ACTIVITY_MESG *activity = (FIT_ACTIVITY_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_ACTIVITY_MESG activity_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_ACTIVITY], &activity_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_ACTIVITY], FIT_ACTIVITY_MESG_DEF_SIZE, fp);
                  activity->timestamp += *offset;
                  activity->local_timestamp += *offset;
                  WriteMessage(local_mesg_number, activity, FIT_ACTIVITY_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_SESSION:
            {
               FIT_SESSION_MESG *session = (FIT_SESSION_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_SESSION_MESG session_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_SESSION], &session_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_SESSION], FIT_SESSION_MESG_DEF_SIZE, fp);
                  session->timestamp += *offset;
                  session->start_time += *offset;
                  WriteMessage(local_mesg_number, session, FIT_SESSION_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_LAP:
            {
               FIT_LAP_MESG *lap = (FIT_LAP_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_LAP_MESG lap_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_LAP], &lap_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_LAP], FIT_LAP_MESG_DEF_SIZE, fp);
                  lap->timestamp += *offset;
                  lap->start_time += *offset;
                  WriteMessage(local_mesg_number, lap, FIT_LAP_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_RECORD:
            {
               FIT_RECORD_MESG *record = (FIT_RECORD_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_RECORD_MESG record_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_RECORD], &record_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_RECORD], FIT_RECORD_MESG_DEF_SIZE, fp);
                  record->timestamp += *offset;
                  WriteMessage(local_mesg_number, record, FIT_RECORD_MESG_SIZE, fp);
               }
               break;
            }

            case FIT_MESG_NUM_EVENT:
            {
               FIT_EVENT_MESG *event = (FIT_EVENT_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_EVENT_MESG event_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_EVENT], &event_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_EVENT], FIT_EVENT_MESG_DEF_SIZE, fp);
                  event->timestamp += *offset;
                  WriteMessage(local_mesg_number, event, FIT_EVENT_MESG_SIZE, fp);
               }
               else
               {
                  if (event->event == FIT_EVENT_TYPE_START)
                  {
                     *start_time = event->timestamp;
                     flag = FIT_TRUE;
                  }
               }
               break;
            }

            case FIT_MESG_NUM_DEVICE_INFO:
            {
               FIT_DEVICE_INFO_MESG *device_info = (FIT_DEVICE_INFO_MESG *)mesg;
               if (*isWrite)
               {
                  FIT_UINT8 local_mesg_number = 0;
                  FIT_DEVICE_INFO_MESG device_info_mesg;
                  Fit_InitMesg(fit_mesg_defs[FIT_MESG_DEVICE_INFO], &device_info_mesg);
                  WriteMessageDefinition(local_mesg_number, fit_mesg_defs[FIT_MESG_DEVICE_INFO], FIT_DEVICE_INFO_MESG_DEF_SIZE, fp);
                  device_info->timestamp += *offset;
                  WriteMessage(local_mesg_number, device_info, FIT_DEVICE_INFO_MESG_SIZE, fp);
               }
               break;
            }

            default:
               printf("War: %u Unknow.\n", mesg_num);
               break;
            }

            break;
         }

         default:
            break;
         }

      } while (convert_return == FIT_CONVERT_MESSAGE_AVAILABLE);

      if (!*isWrite && flag)
      {
         convert_return = FIT_CONVERT_MESSAGE_AVAILABLE;
         break;
      }
   }

   if (convert_return == FIT_CONVERT_ERROR)
   {
      printf("Error decoding file.\n");
      fclose(file);
      return FIT_FALSE;
   }

   if (convert_return == FIT_CONVERT_CONTINUE)
   {
      printf("Unexpected end of file.\n");
      fclose(file);
      return FIT_FALSE;
   }

   if (convert_return == FIT_CONVERT_DATA_TYPE_NOT_SUPPORTED)
   {
      printf("File is not FIT.\n");
      fclose(file);
      return FIT_FALSE;
   }

   if (convert_return == FIT_CONVERT_PROTOCOL_VERSION_NOT_SUPPORTED)
   {
      printf("Protocol version not supported.\n");
      fclose(file);
      return FIT_FALSE;
   }

   // if (convert_return == FIT_CONVERT_END_OF_FILE)
   //    printf("File converted successfully.\n");

   if (*isWrite)
   {
      // Write CRC.
      fwrite(&data_crc, 1, sizeof(FIT_UINT16), fp);

      // Update file header with data size.
      WriteFileHeader(fp);

      fclose(fp);
   }

   fclose(file);

   return FIT_TRUE;
}

void WriteFileHeader(FILE *fp)
{
   FIT_FILE_HDR file_header;

   file_header.header_size = FIT_FILE_HDR_SIZE;
   file_header.profile_version = FIT_PROFILE_VERSION;
   file_header.protocol_version = FIT_PROTOCOL_VERSION_20;
   memcpy((FIT_UINT8 *)&file_header.data_type, ".FIT", 4);
   fseek(fp, 0, SEEK_END);
   file_header.data_size = ftell(fp) - FIT_FILE_HDR_SIZE - sizeof(FIT_UINT16);
   file_header.crc = FitCRC_Calc16(&file_header, FIT_STRUCT_OFFSET(crc, FIT_FILE_HDR));

   fseek(fp, 0, SEEK_SET);
   fwrite((void *)&file_header, 1, FIT_FILE_HDR_SIZE, fp);
}

void WriteMessageDefinition(FIT_UINT8 local_mesg_number, const void *mesg_def_pointer, FIT_UINT16 mesg_def_size, FILE *fp)
{
   FIT_UINT8 header = local_mesg_number | FIT_HDR_TYPE_DEF_BIT;
   WriteData(&header, FIT_HDR_SIZE, fp);
   WriteData(mesg_def_pointer, mesg_def_size, fp);
}

void WriteMessageDefinitionWithDevFields(
    FIT_UINT8 local_mesg_number,
    const void *mesg_def_pointer,
    FIT_UINT8 mesg_def_size,
    FIT_UINT8 number_dev_fields,
    FIT_DEV_FIELD_DEF *dev_field_definitions,
    FILE *fp)
{
   FIT_UINT16 i;
   FIT_UINT8 header = local_mesg_number | FIT_HDR_TYPE_DEF_BIT | FIT_HDR_DEV_DATA_BIT;
   WriteData(&header, FIT_HDR_SIZE, fp);
   WriteData(mesg_def_pointer, mesg_def_size, fp);

   WriteData(&number_dev_fields, sizeof(FIT_UINT8), fp);
   for (i = 0; i < number_dev_fields; i++)
   {
      WriteData(&dev_field_definitions[i], sizeof(FIT_DEV_FIELD_DEF), fp);
   }
}

void WriteMessage(FIT_UINT8 local_mesg_number, const void *mesg_pointer, FIT_UINT16 mesg_size, FILE *fp)
{
   WriteData(&local_mesg_number, FIT_HDR_SIZE, fp);
   WriteData(mesg_pointer, mesg_size, fp);
}

void WriteDeveloperField(const void *data, FIT_UINT16 data_size, FILE *fp)
{
   WriteData(data, data_size, fp);
}

void WriteData(const void *data, FIT_UINT16 data_size, FILE *fp)
{
   FIT_UINT16 offset;

   fwrite(data, 1, data_size, fp);

   for (offset = 0; offset < data_size; offset++)
      data_crc = FitCRC_Get16(data_crc, *((FIT_UINT8 *)data + offset));
}
